---
- name: configure grub
  hosts: all
  tasks:
    - name: ensure net.ifnames parameter is set to 0
      replace:
        path: /etc/default/grub
        regexp: ^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$
        replace: \1 {{ option }}={{ value }}\2
      vars:
        option: net.ifnames
        value: 00

    - name: ensure biosdevname parameter is set to 0
      replace:
        path: /etc/default/grub
        regexp: ^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$
        replace: \1 {{ option }}={{ value }}\2
      vars:
        option: biosdevname
        value: 00

    - name: reconfigure grub
      ansible.builtin.command: grub2-mkconfig
