---
- name: Print usage mode
  ansible.builtin.debug:
    msg: Running role in installation mode.

- name: Install vsftpd
  ansible.builtin.import_tasks: vsftpd-install.yml

- name: Configure vsftpd
  ansible.builtin.import_tasks: vsftpd-configure.yml

- name: Configure firewalld
  ansible.builtin.import_tasks: firewalld-configure.yml
  when: firewalld_configure
