---
#
# There is a best-practice to not run raw bash commands on remote hosts (ex.: cat /etc/passwd)
# So, we use 'ansible.builtin.slurp' module and adding additional task for decoding file content
# to avoid this situation.
#
- name: create or update users from the list
  hosts: all
  vars_files:
    - vars/users.yml
  tasks:
    - name: get /etc/passwd file content
      ansible.builtin.slurp:
        src: /etc/passwd
      register: slurpfile

    - name: print fetched encoded passwd file content
      ansible.builtin.debug:
        var: slurpfile
        verbosity: 1

    - name: populate passwd fact
      ansible.builtin.set_fact:
        passwd: "{{ slurpfile.content | b64decode }}"

    - name: print decoded passw file content
      ansible.builtin.debug:
        var: passwd
        verbosity: 1

    - name: create or update users from the list
      include_tasks: tasks/create-or-update-user.yml
      with_dict: "{{ users }}"
