---
- name: remove users
  hosts: all
  vars_files:
    - vars/users.yml
  tasks:
    - name: remove users from the list
      ansible.builtin.user:
        name: "{{ item.value.username }}"
        state: absent
        remove: true
      with_dict: "{{ users }}"
      no_log: true
