---
- name: remove users
  hosts: all
  vars_files:
    - vars/users.yml
  tasks:
    - name: remove users from the list
      user:
        name: "{{item.value.username}}"
        state: absent
        remove: yes
      with_dict: "{{ users }}"