---
galaxy_info:
  author: Anton Sukhanov
  description: Install and configure the vsftpd service
  license: BSD-3-Clause
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - networking
    - ftp
    - sftp
    - vsftpd
dependencies: []
allow_duplicates: true
